### PR TITLE
Added vim-cedar integration

### PR DESCRIPTION
**Pull request by Dzordzu**

### CODE REVIEW

**Comment by khieta** [comment]
Hi @Dzordzu, thanks for the contribution! We love syntax highlighting 🙂 Two quick suggestions:
* Can you add a link in your README to instructions for vim-plug (e.g., https://github.com/junegunn/vim-plug/wiki/tutorial) for users who may be unfamiliar with vim's plugin system?
* Our preferred filename extension is `.cedar` rather than `.cdr`, so we'd appreciate if you would update your file `ftdetect/cedar.vim` to reflect that. Please let us know if you saw the `.cdr` extension in any of our released documentation so we can fix it. 

Thanks!

**Comment by aaronjeline** [comment]
Just pinging to see if you still want to merge this in, we had a couple of small changes we wanted? Please let us know if we can do anything to help.

**Comment by Dzordzu** [comment]
Hi! Sorry, I've been busy since the beginning of the summer. I will try to do suggested changes in the following week :)

**Comment by Dzordzu** [comment]
When it comes to the `.cdr`: it is shorter and I use it within my project. I just like it. Obviously, I'm adding a standard extension to the ftdetect. Thanks for your patience

**Review by john-h-kastner-aws — APPROVED** [review]

**Review by andrewmwells-amazon — APPROVED** [review]

**Pull request merged**
