### PR TITLE
Add ruby bindings to language support list

### PR DESCRIPTION
**Pull request by elct9620**
*Issue #, if available:*

*Description of changes:*

Add [cedar-policy-rb](https://github.com/elct9620/cedar-policy-rb) gem repository to unofficial language support list.

### CODE REVIEW

**Comment by elct9620** [comment]
Thanks for your help, the typo is fixed.

I will consider `#==` and `#hash` for better comparison behavior.

In the ideal use case, the entities should have unique entities by their ID.

```ruby
entities = CedarPolicy::Entities.new([
  CedarPolicy::Entity.new(
    CedarPolicy::EntityUid.new("User", "1")
  ),
  CedarPolicy::Entity.new(
    CedarPolicy::EntityUid.new("User", "1"),
    { name: "Aotoki" }
  )
])

# The entities is a Set that will check the entity object's hash to keep the entity unique
# => [#<CedarPolicy::Entity @uid=User::"1">]
```

**Comment by john-h-kastner-aws** [comment]
> In the ideal use case, the entities should have unique entities by their ID.

Right, you should be able to compare for equality just be id without looking at attributes, so the `to_hash` comparison isn't necessary. My point about doing any comparison based on `hash` is still relevant. There exist non-equal entity ids that nonetheless hash to the same value.

**Review by khieta — APPROVED** [review]
Thanks for the contribution! Note that on the `main` branch we've moved the `JsonValueWithNoDuplicateKeys` definition to `cedar-policy`, so you'll be able to get rid of your dependency on `cedar-policy-core` in our next major release 🙂 We don't recommend taking a dependency on this crate because we may make breaking changes without respecting semver.

Also, you might want to take a look at our integration tests in https://github.com/cedar-policy/cedar-integration-tests for testing for your code. We use these integration tests currently to check that the [Rust](https://github.com/cedar-policy/cedar), [Java](https://github.com/cedar-policy/cedar-java), and [Go](https://github.com/cedar-policy/cedar-go) behavior match.

**Review by mwhicks1 — APPROVED** [review]

**Comment by elct9620** [comment]
> Thanks for the contribution! Note that on the `main` branch we've moved the `JsonValueWithNoDuplicateKeys` definition to `cedar-policy`, so you'll be able to get rid of your dependency on `cedar-policy-core` in our next major release 🙂 We don't recommend taking a dependency on this crate because we may make breaking changes without respecting semver.
> 
> Also, you might want to take a look at our integration tests in https://github.com/cedar-policy/cedar-integration-tests for testing for your code. We use these integration tests currently to check that the [Rust](https://github.com/cedar-policy/cedar), [Java](https://github.com/cedar-policy/cedar-java), and [Go](https://github.com/cedar-policy/cedar-go) behavior match.

Thanks for your information. I will check for it and add some new tests based on it.

---

> > In the ideal use case, the entities should have unique entities by their ID.
> 
> Right, you should be able to compare for equality just be id without looking at attributes, so the `to_hash` comparison isn't necessary. My point about doing any comparison based on `hash` is still relevant. There exist non-equal entity ids that nonetheless hash to the same value.

I got your point about the "collision" means.

The `#hash` method in Ruby `["1", "b"].hash` may have the same value as another item e.g. `["1", "x"].hash` which causes the different entity to be identified as the same one.

I think it is acceptable because Ruby internally uses this way to calculate the unique key in the `Set` and `Hash` objects.
Reference: https://ruby-doc.org/3.0.7/Object.html#method-i-hash

In the current design, I use `[self.class, @uid].hash` as its hash value which means calculating the `Entity` class hash with the `EntityUid` class value to make it be identified by a unique EntityUid.

I still prefer this way to make it work with native Ruby support. And I believe the Ruby team already makes `#hash` can work in most cases.

References:
* https://github.com/ruby/ruby/blob/master/array.c#L5247-L5261
* https://github.com/ruby/ruby/blob/master/hash.c#L173-L212
* https://github.com/ruby/ruby/blob/master/hash.c#L218-L269

**Pull request merged**
